import type { Metadata } from "next";
import Script from "next/script";
import { ReactNode } from "react";

import { env } from "@/env";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <>
      <Script
        src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${env.NEXT_PUBLIC_KAKAO_MAP_KEY}&libraries=services,clusterer&autoload=false`}
        strategy="beforeInteractive"
      />
      {children}
    </>
  );
}
