import "@radix-ui/themes/styles.css";
import "../styles/globals.css";
import "../styles/reset.css";
import "../styles/theme.css";

import type { Metadata } from "next";
import localFont from "next/font/local";

import MobileLayout from "@/layout/Mobile/MobileLayout";
import RadixThemeProvider from "@/lib/RadixThemeProvider";
import ReactQueryProvider from "@/lib/ReactQueryProvider";
import { cn } from "@/utils/cn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const Pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  variable: "--font-pretendard",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={Pretendard.variable}>
      <body className={cn(Pretendard.className)} suppressHydrationWarning>
        <ReactQueryProvider>
          <RadixThemeProvider>
            <MobileLayout>{children}</MobileLayout>
          </RadixThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
