# .github/workflows/chromatic.yml
name: "Chromatic Deployment"
run-name: Storybook deployment by ${{ github.actor }}

on:
  pull_request:
    types: [opened, ready_for_review]
    branches:
      - develop
    paths:
      - "**/*.stories.tsx"

jobs:
  chromatic:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-build') }}
    name: Run Chromatic Deployment
    # Operating System
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}

    # Job steps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"

      - name: Set up environment variables
        run: |
          echo "NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL" >> .env
          echo "NEXT_PUBLIC_STAGE=$NEXT_PUBLIC_STAGE" >> .env
          echo "AUTH_SECRET=$AUTH_SECRET" >> .env
          echo "AUTH_KAKAO_ID=$AUTH_KAKAO_ID" >> .env
          echo "AUTH_KAKAO_SECRET=$AUTH_KAKAO_SECRET" >> .env
        env:
          NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
          NEXT_PUBLIC_STAGE: ${{ inputs.NEXT_PUBLIC_STAGE }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          AUTH_KAKAO_ID: ${{ secrets.AUTH_KAKAO_ID }}
          AUTH_KAKAO_SECRET: ${{ secrets.AUTH_KAKAO_SECRET }}

      - name: Install dependencies
        run: pnpm install

      - name: Run Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build-storybook
          onlyChanged: true

      - name: comment PR
        uses: thollander/actions-comment-pull-request@v1
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: "💅 스토리북 URL 확인하기 - ${{ steps.chromatic.outputs.storybookUrl }}"
