name: "PR Test"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main, develop]

jobs:
  build:
    uses: ./.github/workflows/_build.yaml
    with:
      NODE_VERSION: 20.x
